
modLoader = "javafml"
loaderVersion = "47"
license = "All rights reserved"

[[mods]]
modId = "scanner"
version = "1.0.0"
displayName = "Block Scanner"
authors = "KantraCity"
description = '''
Adds a scanning devices
'''

[[dependencies.scanner]]
modId = "neoforge"
type = "required"
versionRange = "21.1.186"

[[dependencies.scanner]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.0]"
